[theme]
primaryColor = '#379683'  # Green (strong and energetic)
backgroundColor = '#F4FFFA' # Light green (calm and refreshing)
secondaryBackgroundColor = '#EEFAE9'  # Pale green (relaxing and inviting)
textColor = '#1A3D1A'